
import React, { createContext, useContext, useEffect, useState } from 'react';

// Define languages
type Language = 'english' | 'spanish' | 'french' | 'german' | 'italian' | 'portuguese' | 'turkish' | 'arabic' | 'simplified-chinese' | 'traditional-chinese' | 'korean' | 'norwegian';

// Simple translations map
const translations: Record<Language, Record<string, string>> = {
  english: {
    'settings.theme': 'Theme',
    'settings.languages': 'Languages',
    'theme.light': 'Light',
    'theme.dark': 'Dark',
    'theme.system': 'System',
    'sidebar.home': 'Home',
    'sidebar.newTask': 'New Task',
    'sidebar.today': 'Today',
    'sidebar.noMoreConversations': 'No more conversations',
    'dashboard.header': 'How can I help you today?',
    'dashboard.agents': 'All Agents',
    'dashboard.coding': 'Coding',
    'dashboard.testing': 'Testing',
    'dashboard.documentation': 'Documentation',
    'dashboard.insights': 'Code Insights',
    'workspace.create': 'Create Workspace',
    'workspace.personal': 'Personal Workspace',
    'workspace.namePlaceholder': 'Enter workspace name',
    'workspace.created': 'Workspace Created',
    'workspace.createdSuccess': '{name} workspace has been created successfully',
    'workspace.error': 'Error',
    'workspace.nameRequired': 'Workspace name is required',
    'common.submit': 'Submit',
    'common.cancel': 'Cancel',
    'common.error': 'Error',
    'auth.signOut': 'Sign out',
    'auth.signedOut': 'Signed out successfully',
    'auth.signedOutSuccess': 'You have been signed out of your account.',
    'auth.signOutError': 'Failed to sign out. Please try again.',
    'settings.general': 'General',
    'settings.user': 'User',
    'settings.workspace': 'Workspace',
    'settings.repositories': 'Repositories',
    'settings.indexes': 'Indexes',
    'settings.pageTitle': 'Settings',
    'settings.name': 'Name',
    'settings.email': 'Email',
    'settings.password': 'Password',
    'settings.sessions': 'Sessions',
    'settings.accessLogs': 'Access Logs',
    'settings.currentDevice': 'Current Device',
    'settings.lastActive': 'Last Active',
    'settings.logout': 'Logout',
    'settings.device': 'Device',
    'settings.ipAddress': 'IP Address',
    'settings.action': 'Action',
    'settings.time': 'Time',
    'settings.deleteAccount': 'Delete my account',
    'settings.changePassword': 'Change Password',
    'settings.edit': 'Edit',
    'settings.save': 'Save',
    'settings.noUsername': 'No username set',
  },
  spanish: {
    'settings.theme': 'Tema',
    'settings.languages': 'Idiomas',
    'theme.light': 'Claro',
    'theme.dark': 'Oscuro',
    'theme.system': 'Sistema',
    'sidebar.home': 'Inicio',
    'sidebar.newTask': 'Nueva Tarea',
    'sidebar.today': 'Hoy',
    'sidebar.noMoreConversations': 'No hay más conversaciones',
    'dashboard.header': '¿Cómo puedo ayudarte hoy?',
    'dashboard.agents': 'Todos los Agentes',
    'dashboard.coding': 'Codificación',
    'dashboard.testing': 'Pruebas',
    'dashboard.documentation': 'Documentación',
    'dashboard.insights': 'Análisis de Código',
    'workspace.create': 'Crear Espacio de Trabajo',
    'workspace.personal': 'Espacio de Trabajo Personal',
    'workspace.namePlaceholder': 'Ingrese nombre del espacio de trabajo',
    'workspace.created': 'Espacio de Trabajo Creado',
    'workspace.createdSuccess': 'El espacio de trabajo {name} ha sido creado con éxito',
    'workspace.error': 'Error',
    'workspace.nameRequired': 'Se requiere el nombre del espacio de trabajo',
    'common.submit': 'Enviar',
    'common.cancel': 'Cancelar',
    'common.error': 'Error',
    'auth.signOut': 'Cerrar sesión',
    'auth.signedOut': 'Sesión cerrada con éxito',
    'auth.signedOutSuccess': 'Has cerrado sesión en tu cuenta.',
    'auth.signOutError': 'Error al cerrar sesión. Por favor, inténtalo de nuevo.',
    'settings.general': 'General',
    'settings.user': 'Usuario',
    'settings.workspace': 'Espacio de Trabajo',
    'settings.repositories': 'Repositorios',
    'settings.indexes': 'Índices',
    'settings.pageTitle': 'Configuración',
    'settings.name': 'Nombre',
    'settings.email': 'Correo electrónico',
    'settings.password': 'Contraseña',
    'settings.sessions': 'Sesiones',
    'settings.accessLogs': 'Registros de Acceso',
    'settings.currentDevice': 'Dispositivo Actual',
    'settings.lastActive': 'Último Activo',
    'settings.logout': 'Cerrar Sesión',
    'settings.device': 'Dispositivo',
    'settings.ipAddress': 'Dirección IP',
    'settings.action': 'Acción',
    'settings.time': 'Tiempo',
    'settings.deleteAccount': 'Eliminar mi cuenta',
    'settings.changePassword': 'Cambiar Contraseña',
    'settings.edit': 'Editar',
    'settings.save': 'Guardar',
    'settings.noUsername': 'Sin nombre de usuario',
  },
  french: {
    'settings.theme': 'Thème',
    'settings.languages': 'Langues',
    'theme.light': 'Clair',
    'theme.dark': 'Sombre',
    'theme.system': 'Système',
    'sidebar.home': 'Accueil',
    'sidebar.newTask': 'Nouvelle Tâche',
    'sidebar.today': 'Aujourd\'hui',
    'sidebar.noMoreConversations': 'Pas plus de conversations',
    'dashboard.header': 'Comment puis-je vous aider aujourd\'hui?',
    'dashboard.agents': 'Tous les Agents',
    'dashboard.coding': 'Codage',
    'dashboard.testing': 'Tests',
    'dashboard.documentation': 'Documentation',
    'dashboard.insights': 'Analyse de Code',
    'workspace.create': 'Créer un Espace de Travail',
    'workspace.personal': 'Espace de Travail Personnel',
    'workspace.namePlaceholder': 'Entrez le nom de l\'espace de travail',
    'workspace.created': 'Espace de Travail Créé',
    'workspace.createdSuccess': 'L\'espace de travail {name} a été créé avec succès',
    'workspace.error': 'Erreur',
    'workspace.nameRequired': 'Le nom de l\'espace de travail est requis',
    'common.submit': 'Soumettre',
    'common.cancel': 'Annuler',
    'common.error': 'Erreur',
    'auth.signOut': 'Déconnexion',
    'auth.signedOut': 'Déconnecté avec succès',
    'auth.signedOutSuccess': 'Vous avez été déconnecté de votre compte.',
    'auth.signOutError': 'Échec de la déconnexion. Veuillez réessayer.',
    'settings.general': 'Général',
    'settings.user': 'Utilisateur',
    'settings.workspace': 'Espace de Travail',
    'settings.repositories': 'Dépôts',
    'settings.indexes': 'Index',
    'settings.pageTitle': 'Paramètres',
    'settings.name': 'Nom',
    'settings.email': 'Email',
    'settings.password': 'Mot de passe',
    'settings.sessions': 'Sessions',
    'settings.accessLogs': 'Journaux d\'Accès',
    'settings.currentDevice': 'Appareil Actuel',
    'settings.lastActive': 'Dernière Activité',
    'settings.logout': 'Déconnexion',
    'settings.device': 'Appareil',
    'settings.ipAddress': 'Adresse IP',
    'settings.action': 'Action',
    'settings.time': 'Temps',
    'settings.deleteAccount': 'Supprimer mon compte',
    'settings.changePassword': 'Changer le Mot de Passe',
    'settings.edit': 'Modifier',
    'settings.save': 'Sauvegarder',
    'settings.noUsername': 'Aucun nom d\'utilisateur',
  },
  german: {
    'settings.theme': 'Thema',
    'settings.languages': 'Sprachen',
    'theme.light': 'Hell',
    'theme.dark': 'Dunkel',
    'theme.system': 'System',
    'sidebar.home': 'Startseite',
    'sidebar.newTask': 'Neue Aufgabe',
    'sidebar.today': 'Heute',
    'sidebar.noMoreConversations': 'Keine weiteren Gespräche',
    'dashboard.header': 'Wie kann ich Ihnen heute helfen?',
    'dashboard.agents': 'Alle Agenten',
    'dashboard.coding': 'Programmierung',
    'dashboard.testing': 'Tests',
    'dashboard.documentation': 'Dokumentation',
    'dashboard.insights': 'Code-Einblicke',
    'workspace.create': 'Arbeitsbereich Erstellen',
    'workspace.personal': 'Persönlicher Arbeitsbereich',
    'workspace.namePlaceholder': 'Arbeitsbereichsname eingeben',
    'workspace.created': 'Arbeitsbereich Erstellt',
    'workspace.createdSuccess': 'Arbeitsbereich {name} wurde erfolgreich erstellt',
    'workspace.error': 'Fehler',
    'workspace.nameRequired': 'Arbeitsbereichsname ist erforderlich',
    'common.submit': 'Absenden',
    'common.cancel': 'Abbrechen',
    'common.error': 'Fehler',
    'auth.signOut': 'Abmelden',
    'auth.signedOut': 'Erfolgreich abgemeldet',
    'auth.signedOutSuccess': 'Sie wurden von Ihrem Konto abgemeldet.',
    'auth.signOutError': 'Abmelden fehlgeschlagen. Bitte versuchen Sie es erneut.',
    'settings.general': 'Allgemein',
    'settings.user': 'Benutzer',
    'settings.workspace': 'Arbeitsbereich',
    'settings.repositories': 'Repositories',
    'settings.indexes': 'Indizes',
    'settings.pageTitle': 'Einstellungen',
    'settings.name': 'Name',
    'settings.email': 'E-Mail',
    'settings.password': 'Passwort',
    'settings.sessions': 'Sitzungen',
    'settings.accessLogs': 'Zugriffsprotokolle',
    'settings.currentDevice': 'Aktuelles Gerät',
    'settings.lastActive': 'Zuletzt Aktiv',
    'settings.logout': 'Abmelden',
    'settings.device': 'Gerät',
    'settings.ipAddress': 'IP-Adresse',
    'settings.action': 'Aktion',
    'settings.time': 'Zeit',
    'settings.deleteAccount': 'Mein Konto löschen',
    'settings.changePassword': 'Passwort Ändern',
    'settings.edit': 'Bearbeiten',
    'settings.save': 'Speichern',
    'settings.noUsername': 'Kein Benutzername',
  },
  italian: {
    'settings.theme': 'Tema',
    'settings.languages': 'Lingue',
    'theme.light': 'Chiaro',
    'theme.dark': 'Scuro',
    'theme.system': 'Sistema',
    'sidebar.home': 'Home',
    'sidebar.newTask': 'Nuovo Compito',
    'sidebar.today': 'Oggi',
    'sidebar.noMoreConversations': 'Nessun\'altra conversazione',
    'dashboard.header': 'Come posso aiutarti oggi?',
    'dashboard.agents': 'Tutti gli Agenti',
    'dashboard.coding': 'Codifica',
    'dashboard.testing': 'Test',
    'dashboard.documentation': 'Documentazione',
    'dashboard.insights': 'Analisi del Codice',
    'workspace.create': 'Crea Spazio di Lavoro',
    'workspace.personal': 'Spazio di Lavoro Personale',
    'workspace.namePlaceholder': 'Inserisci nome dello spazio di lavoro',
    'workspace.created': 'Spazio di Lavoro Creato',
    'workspace.createdSuccess': 'Lo spazio di lavoro {name} è stato creato con successo',
    'workspace.error': 'Errore',
    'workspace.nameRequired': 'Il nome dello spazio di lavoro è obbligatorio',
    'common.submit': 'Invia',
    'common.cancel': 'Annulla',
    'common.error': 'Errore',
    'auth.signOut': 'Esci',
    'auth.signedOut': 'Disconnesso con successo',
    'auth.signedOutSuccess': 'Sei stato disconnesso dal tuo account.',
    'auth.signOutError': 'Disconnessione fallita. Riprova.',
    'settings.general': 'Generale',
    'settings.user': 'Utente',
    'settings.workspace': 'Spazio di Lavoro',
    'settings.repositories': 'Repository',
    'settings.indexes': 'Indici',
    'settings.pageTitle': 'Impostazioni',
    'settings.name': 'Nome',
    'settings.email': 'Email',
    'settings.password': 'Password',
    'settings.sessions': 'Sessioni',
    'settings.accessLogs': 'Registri di Accesso',
    'settings.currentDevice': 'Dispositivo Attuale',
    'settings.lastActive': 'Ultima Attività',
    'settings.logout': 'Esci',
    'settings.device': 'Dispositivo',
    'settings.ipAddress': 'Indirizzo IP',
    'settings.action': 'Azione',
    'settings.time': 'Ora',
    'settings.deleteAccount': 'Elimina il mio account',
    'settings.changePassword': 'Cambia Password',
    'settings.edit': 'Modifica',
    'settings.save': 'Salva',
    'settings.noUsername': 'Nessun nome utente',
  },
  portuguese: {
    'settings.theme': 'Tema',
    'settings.languages': 'Idiomas',
    'theme.light': 'Claro',
    'theme.dark': 'Escuro',
    'theme.system': 'Sistema',
    'sidebar.home': 'Início',
    'sidebar.newTask': 'Nova Tarefa',
    'sidebar.today': 'Hoje',
    'sidebar.noMoreConversations': 'Não há mais conversas',
    'dashboard.header': 'Como posso ajudar você hoje?',
    'dashboard.agents': 'Todos os Agentes',
    'dashboard.coding': 'Codificação',
    'dashboard.testing': 'Testes',
    'dashboard.documentation': 'Documentação',
    'dashboard.insights': 'Análise de Código',
    'workspace.create': 'Criar Espaço de Trabalho',
    'workspace.personal': 'Espaço de Trabalho Pessoal',
    'workspace.namePlaceholder': 'Digite o nome do espaço de trabalho',
    'workspace.created': 'Espaço de Trabalho Criado',
    'workspace.createdSuccess': 'O espaço de trabalho {name} foi criado com sucesso',
    'workspace.error': 'Erro',
    'workspace.nameRequired': 'O nome do espaço de trabalho é obrigatório',
    'common.submit': 'Enviar',
    'common.cancel': 'Cancelar',
    'common.error': 'Erro',
    'auth.signOut': 'Sair',
    'auth.signedOut': 'Saiu com sucesso',
    'auth.signedOutSuccess': 'Você saiu da sua conta.',
    'auth.signOutError': 'Falha ao sair. Por favor, tente novamente.',
    'settings.general': 'Geral',
    'settings.user': 'Usuário',
    'settings.workspace': 'Espaço de Trabalho',
    'settings.repositories': 'Repositórios',
    'settings.indexes': 'Índices',
    'settings.pageTitle': 'Configurações',
    'settings.name': 'Nome',
    'settings.email': 'Email',
    'settings.password': 'Senha',
    'settings.sessions': 'Sessões',
    'settings.accessLogs': 'Registros de Acesso',
    'settings.currentDevice': 'Dispositivo Atual',
    'settings.lastActive': 'Última Atividade',
    'settings.logout': 'Sair',
    'settings.device': 'Dispositivo',
    'settings.ipAddress': 'Endereço IP',
    'settings.action': 'Ação',
    'settings.time': 'Tempo',
    'settings.deleteAccount': 'Excluir minha conta',
    'settings.changePassword': 'Alterar Senha',
    'settings.edit': 'Editar',
    'settings.save': 'Salvar',
    'settings.noUsername': 'Sem nome de usuário',
  },
  turkish: {
    'settings.theme': 'Tema',
    'settings.languages': 'Diller',
    'theme.light': 'Açık',
    'theme.dark': 'Koyu',
    'theme.system': 'Sistem',
    'sidebar.home': 'Ana Sayfa',
    'sidebar.newTask': 'Yeni Görev',
    'sidebar.today': 'Bugün',
    'sidebar.noMoreConversations': 'Başka konuşma yok',
    'dashboard.header': 'Bugün size nasıl yardımcı olabilirim?',
    'dashboard.agents': 'Tüm Ajanlar',
    'dashboard.coding': 'Kodlama',
    'dashboard.testing': 'Test',
    'dashboard.documentation': 'Dokümantasyon',
    'dashboard.insights': 'Kod Analizleri',
    'workspace.create': 'Çalışma Alanı Oluştur',
    'workspace.personal': 'Kişisel Çalışma Alanı',
    'workspace.namePlaceholder': 'Çalışma alanı adı girin',
    'workspace.created': 'Çalışma Alanı Oluşturuldu',
    'workspace.createdSuccess': '{name} çalışma alanı başarıyla oluşturuldu',
    'workspace.error': 'Hata',
    'workspace.nameRequired': 'Çalışma alanı adı gereklidir',
    'common.submit': 'Gönder',
    'common.cancel': 'İptal',
    'common.error': 'Hata',
    'auth.signOut': 'Çıkış Yap',
    'auth.signedOut': 'Başarıyla çıkış yapıldı',
    'auth.signedOutSuccess': 'Hesabınızdan çıkış yaptınız.',
    'auth.signOutError': 'Çıkış başarısız. Lütfen tekrar deneyin.',
    'settings.general': 'Genel',
    'settings.user': 'Kullanıcı',
    'settings.workspace': 'Çalışma Alanı',
    'settings.repositories': 'Depolar',
    'settings.indexes': 'İndeksler',
    'settings.pageTitle': 'Ayarlar',
    'settings.name': 'İsim',
    'settings.email': 'E-posta',
    'settings.password': 'Parola',
    'settings.sessions': 'Oturumlar',
    'settings.accessLogs': 'Erişim Kayıtları',
    'settings.currentDevice': 'Mevcut Cihaz',
    'settings.lastActive': 'Son Aktivite',
    'settings.logout': 'Çıkış Yap',
    'settings.device': 'Cihaz',
    'settings.ipAddress': 'IP Adresi',
    'settings.action': 'Eylem',
    'settings.time': 'Zaman',
    'settings.deleteAccount': 'Hesabımı sil',
    'settings.changePassword': 'Parola Değiştir',
    'settings.edit': 'Düzenle',
    'settings.save': 'Kaydet',
    'settings.noUsername': 'Kullanıcı adı yok',
  },
  arabic: {
    'settings.theme': 'المظهر',
    'settings.languages': 'اللغات',
    'theme.light': 'فاتح',
    'theme.dark': 'داكن',
    'theme.system': 'النظام',
    'sidebar.home': 'الرئيسية',
    'sidebar.newTask': 'مهمة جديدة',
    'sidebar.today': 'اليوم',
    'sidebar.noMoreConversations': 'لا توجد محادثات أخرى',
    'dashboard.header': 'كيف يمكنني مساعدتك اليوم؟',
    'dashboard.agents': 'جميع العملاء',
    'dashboard.coding': 'البرمجة',
    'dashboard.testing': 'الاختبار',
    'dashboard.documentation': 'التوثيق',
    'dashboard.insights': 'تحليلات الكود',
    'workspace.create': 'إنشاء مساحة عمل',
    'workspace.personal': 'مساحة العمل الشخصية',
    'workspace.namePlaceholder': 'أدخل اسم مساحة العمل',
    'workspace.created': 'تم إنشاء مساحة العمل',
    'workspace.createdSuccess': 'تم إنشاء مساحة العمل {name} بنجاح',
    'workspace.error': 'خطأ',
    'workspace.nameRequired': 'اسم مساحة العمل مطلوب',
    'common.submit': 'إرسال',
    'common.cancel': 'إلغاء',
    'common.error': 'خطأ',
    'auth.signOut': 'تسجيل الخروج',
    'auth.signedOut': 'تم تسجيل الخروج بنجاح',
    'auth.signedOutSuccess': 'لقد تم تسجيل خروجك من حسابك.',
    'auth.signOutError': 'فشل تسجيل الخروج. يرجى المحاولة مرة أخرى.',
    'settings.general': 'عام',
    'settings.user': 'المستخدم',
    'settings.workspace': 'مساحة العمل',
    'settings.repositories': 'المستودعات',
    'settings.indexes': 'الفهارس',
    'settings.pageTitle': 'الإعدادات',
    'settings.name': 'الاسم',
    'settings.email': 'البريد الإلكتروني',
    'settings.password': 'كلمة المرور',
    'settings.sessions': 'الجلسات',
    'settings.accessLogs': 'سجلات الوصول',
    'settings.currentDevice': 'الجهاز الحالي',
    'settings.lastActive': 'آخر نشاط',
    'settings.logout': 'تسجيل الخروج',
    'settings.device': 'الجهاز',
    'settings.ipAddress': 'عنوان IP',
    'settings.action': 'الإجراء',
    'settings.time': 'الوقت',
    'settings.deleteAccount': 'حذف حسابي',
    'settings.changePassword': 'تغيير كلمة المرور',
    'settings.edit': 'تعديل',
    'settings.save': 'حفظ',
    'settings.noUsername': 'لم يتم تعيين اسم المستخدم',
  },
  'simplified-chinese': {
    'settings.theme': '主题',
    'settings.languages': '语言',
    'theme.light': '浅色',
    'theme.dark': '深色',
    'theme.system': '系统',
    'sidebar.home': '首页',
    'sidebar.newTask': '新任务',
    'sidebar.today': '今天',
    'sidebar.noMoreConversations': '没有更多对话',
    'dashboard.header': '今天我能帮您什么？',
    'dashboard.agents': '所有代理',
    'dashboard.coding': '编程',
    'dashboard.testing': '测试',
    'dashboard.documentation': '文档',
    'dashboard.insights': '代码分析',
    'workspace.create': '创建工作区',
    'workspace.personal': '个人工作区',
    'workspace.namePlaceholder': '输入工作区名称',
    'workspace.created': '工作区已创建',
    'workspace.createdSuccess': '工作区 {name} 已成功创建',
    'workspace.error': '错误',
    'workspace.nameRequired': '工作区名称是必需的',
    'common.submit': '提交',
    'common.cancel': '取消',
    'common.error': '错误',
    'auth.signOut': '退出登录',
    'auth.signedOut': '已成功退出登录',
    'auth.signedOutSuccess': '您已退出登录。',
    'auth.signOutError': '退出登录失败。请重试。',
    'settings.general': '常规',
    'settings.user': '用户',
    'settings.workspace': '工作区',
    'settings.repositories': '代码仓库',
    'settings.indexes': '索引',
    'settings.pageTitle': '设置',
    'settings.name': '姓名',
    'settings.email': '电子邮件',
    'settings.password': '密码',
    'settings.sessions': '会话',
    'settings.accessLogs': '访问日志',
    'settings.currentDevice': '当前设备',
    'settings.lastActive': '最后活动',
    'settings.logout': '退出登录',
    'settings.device': '设备',
    'settings.ipAddress': 'IP地址',
    'settings.action': '操作',
    'settings.time': '时间',
    'settings.deleteAccount': '删除我的账户',
    'settings.changePassword': '更改密码',
    'settings.edit': '编辑',
    'settings.save': '保存',
    'settings.noUsername': '未设置用户名',
  },
  'traditional-chinese': {
    'settings.theme': '主題',
    'settings.languages': '語言',
    'theme.light': '淺色',
    'theme.dark': '深色',
    'theme.system': '系統',
    'sidebar.home': '首頁',
    'sidebar.newTask': '新任務',
    'sidebar.today': '今天',
    'sidebar.noMoreConversations': '沒有更多對話',
    'dashboard.header': '今天我能幫您什麼？',
    'dashboard.agents': '所有代理',
    'dashboard.coding': '編程',
    'dashboard.testing': '測試',
    'dashboard.documentation': '文檔',
    'dashboard.insights': '代碼分析',
    'workspace.create': '創建工作區',
    'workspace.personal': '個人工作區',
    'workspace.namePlaceholder': '輸入工作區名稱',
    'workspace.created': '工作區已創建',
    'workspace.createdSuccess': '工作區 {name} 已成功創建',
    'workspace.error': '錯誤',
    'workspace.nameRequired': '工作區名稱是必需的',
    'common.submit': '提交',
    'common.cancel': '取消',
    'common.error': '錯誤',
    'auth.signOut': '退出登錄',
    'auth.signedOut': '已成功退出登錄',
    'auth.signedOutSuccess': '您已退出登錄。',
    'auth.signOutError': '退出登錄失敗。請重試。',
    'settings.general': '常規',
    'settings.user': '用戶',
    'settings.workspace': '工作區',
    'settings.repositories': '代碼倉庫',
    'settings.indexes': '索引',
    'settings.pageTitle': '設置',
    'settings.name': '姓名',
    'settings.email': '電子郵件',
    'settings.password': '密碼',
    'settings.sessions': '會話',
    'settings.accessLogs': '訪問日誌',
    'settings.currentDevice': '當前設備',
    'settings.lastActive': '最後活動',
    'settings.logout': '退出登錄',
    'settings.device': '設備',
    'settings.ipAddress': 'IP地址',
    'settings.action': '操作',
    'settings.time': '時間',
    'settings.deleteAccount': '刪除我的賬戶',
    'settings.changePassword': '更改密碼',
    'settings.edit': '編輯',
    'settings.save': '保存',
    'settings.noUsername': '未設置用戶名',
  },
  korean: {
    'settings.theme': '테마',
    'settings.languages': '언어',
    'theme.light': '라이트',
    'theme.dark': '다크',
    'theme.system': '시스템',
    'sidebar.home': '홈',
    'sidebar.newTask': '새 작업',
    'sidebar.today': '오늘',
    'sidebar.noMoreConversations': '더 이상 대화 없음',
    'dashboard.header': '오늘 어떻게 도와드릴까요?',
    'dashboard.agents': '모든 에이전트',
    'dashboard.coding': '코딩',
    'dashboard.testing': '테스트',
    'dashboard.documentation': '문서',
    'dashboard.insights': '코드 인사이트',
    'workspace.create': '작업 공간 만들기',
    'workspace.personal': '개인 작업 공간',
    'workspace.namePlaceholder': '작업 공간 이름 입력',
    'workspace.created': '작업 공간 생성됨',
    'workspace.createdSuccess': '{name} 작업 공간이 성공적으로 생성되었습니다',
    'workspace.error': '오류',
    'workspace.nameRequired': '작업 공간 이름이 필요합니다',
    'common.submit': '제출',
    'common.cancel': '취소',
    'common.error': '오류',
    'auth.signOut': '로그아웃',
    'auth.signedOut': '성공적으로 로그아웃되었습니다',
    'auth.signedOutSuccess': '계정에서 로그아웃되었습니다.',
    'auth.signOutError': '로그아웃 실패. 다시 시도해주세요.',
    'settings.general': '일반',
    'settings.user': '사용자',
    'settings.workspace': '작업 공간',
    'settings.repositories': '저장소',
    'settings.indexes': '인덱스',
    'settings.pageTitle': '설정',
    'settings.name': '이름',
    'settings.email': '이메일',
    'settings.password': '비밀번호',
    'settings.sessions': '세션',
    'settings.accessLogs': '접근 로그',
    'settings.currentDevice': '현재 기기',
    'settings.lastActive': '마지막 활동',
    'settings.logout': '로그아웃',
    'settings.device': '기기',
    'settings.ipAddress': 'IP 주소',
    'settings.action': '작업',
    'settings.time': '시간',
    'settings.deleteAccount': '내 계정 삭제',
    'settings.changePassword': '비밀번호 변경',
    'settings.edit': '편집',
    'settings.save': '저장',
    'settings.noUsername': '사용자 이름 없음',
  },
  norwegian: {
    'settings.theme': 'Tema',
    'settings.languages': 'Språk',
    'theme.light': 'Lys',
    'theme.dark': 'Mørk',
    'theme.system': 'System',
    'sidebar.home': 'Hjem',
    'sidebar.newTask': 'Ny Oppgave',
    'sidebar.today': 'I dag',
    'sidebar.noMoreConversations': 'Ingen flere samtaler',
    'dashboard.header': 'Hvordan kan jeg hjelpe deg i dag?',
    'dashboard.agents': 'Alle Agenter',
    'dashboard.coding': 'Koding',
    'dashboard.testing': 'Testing',
    'dashboard.documentation': 'Dokumentasjon',
    'dashboard.insights': 'Kodeanalyse',
    'workspace.create': 'Opprett Arbeidsområde',
    'workspace.personal': 'Personlig Arbeidsområde',
    'workspace.namePlaceholder': 'Skriv navn på arbeidsområde',
    'workspace.created': 'Arbeidsområde Opprettet',
    'workspace.createdSuccess': 'Arbeidsområdet {name} har blitt opprettet',
    'workspace.error': 'Feil',
    'workspace.nameRequired': 'Navn på arbeidsområde er påkrevd',
    'common.submit': 'Send inn',
    'common.cancel': 'Avbryt',
    'common.error': 'Feil',
    'auth.signOut': 'Logg ut',
    'auth.signedOut': 'Logget ut',
    'auth.signedOutSuccess': 'Du har blitt logget ut av kontoen din.',
    'auth.signOutError': 'Kunne ikke logge ut. Vennligst prøv igjen.',
    'settings.general': 'Generelt',
    'settings.user': 'Bruker',
    'settings.workspace': 'Arbeidsområde',
    'settings.repositories': 'Kodelager',
    'settings.indexes': 'Indekser',
    'settings.pageTitle': 'Innstillinger',
    'settings.name': 'Navn',
    'settings.email': 'E-post',
    'settings.password': 'Passord',
    'settings.sessions': 'Økter',
    'settings.accessLogs': 'Tilgangslogger',
    'settings.currentDevice': 'Nåværende Enhet',
    'settings.lastActive': 'Sist Aktiv',
    'settings.logout': 'Logg ut',
    'settings.device': 'Enhet',
    'settings.ipAddress': 'IP-adresse',
    'settings.action': 'Handling',
    'settings.time': 'Tid',
    'settings.deleteAccount': 'Slett kontoen min',
    'settings.changePassword': 'Endre Passord',
    'settings.edit': 'Rediger',
    'settings.save': 'Lagre',
    'settings.noUsername': 'Ingen brukernavn',
  }
};

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string, params?: Record<string, string>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: React.ReactNode }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const savedLanguage = localStorage.getItem('APL_language');
    return (savedLanguage as Language) || 'english';
  });

  useEffect(() => {
    localStorage.setItem('APL_language', language);
  }, [language]);

  // Translation function with parameter support
  const t = (key: string, params?: Record<string, string>): string => {
    let translation = translations[language][key] || key;
    
    if (params) {
      Object.entries(params).forEach(([param, value]) => {
        translation = translation.replace(`{${param}}`, value);
      });
    }
    
    return translation;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
